trigger:
- main

pool:
  name: 'ADOAgentPool'

variables:
  terraformVersion: '1.6.6'
  workingDir: 'Terraform-Postgres-ADO'
  azureServiceConnection: 'ado-BAL'
  backendResourceGroup: 'rg-BAL'
  backendStorageAccount: 'bhuvanstrgacc123'
  backendContainer: 'adocontainer'
  backendKey: 'storage-infra.tfstate'

stages:

- stage: Terraform_Init
  displayName: Terraform Init
  jobs:
  - job: Init
    steps:
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(terraformVersion)

    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workingDir)
        backendServiceArm: $(azureServiceConnection)
        backendAzureRmResourceGroupName: $(backendResourceGroup)
        backendAzureRmStorageAccountName: $(backendStorageAccount)
        backendAzureRmContainerName: $(backendContainer)
        backendAzureRmKey: $(backendKey)
        commandOptions: '-reconfigure'

- stage: Terraform_Plan
  displayName: Terraform Plan
  dependsOn: Terraform_Init
  jobs:
  - job: Plan
    steps:
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(terraformVersion)

    # REQUIRED: init again
    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workingDir)
        backendServiceArm: $(azureServiceConnection)
        backendAzureRmResourceGroupName: $(backendResourceGroup)
        backendAzureRmStorageAccountName: $(backendStorageAccount)
        backendAzureRmContainerName: $(backendContainer)
        backendAzureRmKey: $(backendKey)
        commandOptions: '-reconfigure'


    - task: TerraformTaskV4@4
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(workingDir)
        environmentServiceNameAzureRM: $(azureServiceConnection)

- stage: Terraform_Apply
  displayName: Terraform Apply
  dependsOn: Terraform_Plan
  jobs:
  - deployment: Apply
    environment: tf-apply-deploy
    strategy:
      runOnce:
        deploy:
          steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: $(terraformVersion)

# REQUIRED: init again
          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: $(workingDir)
              backendServiceArm: $(azureServiceConnection)
              backendAzureRmResourceGroupName: $(backendResourceGroup)
              backendAzureRmStorageAccountName: $(backendStorageAccount)
              backendAzureRmContainerName: $(backendContainer)
              backendAzureRmKey: $(backendKey)
              commandOptions: '-reconfigure'

          - task: TerraformTaskV4@4
            displayName: Terraform Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: $(workingDir)
              environmentServiceNameAzureRM: $(azureServiceConnection)
              commandOptions: '-auto-approve'